services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=mlops
    volumes:
      - ./local-data/postgres/data:/var/lib/postgresql/data
    networks:
      - postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U fede -d postgres" ]
      interval: 10s
      timeout: 8s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - ./local-data/pgadmin/var_lib:/var/lib/pgadmin
      - ./local-data/pgadmin/server:/pgadmin4/servers.json
    depends_on:
      - postgres
    networks:
      - postgres
      - dagster

  dbt:
    build: ./dbt
    image: dbt-postgres
    volumes:
      - ./dbt/src:/code
      - /home/fede/.dbt/profiles.yml:/root/.dbt/profiles.yml
    depends_on:
      - postgres
    networks:
      - postgres
    command: [ "sleep", "infinity" ]

  dagster_db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_DB=dagster
    networks:
      - dagster
    volumes:
      - ./local-data/dagster_db/data:/var/lib/postgresql/data
    expose:
      - 5432

networks:
  postgres:
  dagster:
