
version: 2

sources:
  - name: source_tables
    description: "Tables imported from CSV"
    database: mlops
    schema: source_csv
    tables:
      - name: peliculas_csv
        meta:
          dagster:
            asset_key:  "peliculas_csv" 
      - name: scores_csv
        meta:
          dagster:
            asset_key: "scores_csv" 
      - name: usuarios_csv
        meta:
          dagster:
            asset_key:  "usuarios_csv" 