SELECT 
	CAST( "id" as INT ) as movie_id,
	"Name" as name,
	CAST( CAST("War" as INT) as  BOOL ) as war,
	CAST( CAST("Crime" as INT) as  BOOL ) as crime,
	CAST( CAST("Drama" as INT) as  BOOL ) as drama,
	CAST( CAST("Action" as INT) as  BOOL ) as "action",
	CAST( CAST("Comedy" as INT) as  BOOL ) as comedy,
	CAST( CAST("Horror" as INT) as  BOOL ) as horror,
	CAST( CAST("Sci_Fi" as INT) as  BOOL ) as sci_fi,
	CAST( CAST("Fantasy" as INT) as  BOOL ) as fantasy,
	CAST( CAST("Musical" as INT) as  BOOL ) as musical,
	CAST( CAST("Mystery" as INT) as  BOOL ) as mystery,
	CAST( CAST("Romance" as INT) as  BOOL ) as romance,
	CAST( CAST("Western" as INT) as  BOOL ) as western,
	CAST( CAST("unknown" as INT) as  BOOL ) as "unknown",
	CAST( CAST("Thriller" as INT) as  BOOL ) as thriller,
	CAST( CAST("Adventure" as INT) as  BOOL ) as adventure,
	CAST( CAST("Animation" as INT) as  BOOL ) as animation,
	CAST( CAST("Film_Noir" as INT) as  BOOL ) as film_noir,
	CAST( CAST("Children_s" as INT) as  BOOL ) as childrens,
	CAST( CAST("Documentary" as INT) as  BOOL ) as documentary,
	TO_DATE("Release_Date", 'YY-MM-DD') as release_date
FROM {{ source( 'source_tables', 'peliculas_csv' ) }}